const movies = [
    {
        title: "The Shawshank Redemption", time: "142 دقیقه", year: 1994, imdbScore: 9.3, country: "آمریکا", director: "Frank Darabont", stars: ["Tim Robbins", "https://variety.com/wp-content/uploads/2023/04/Collage-Maker-26-Apr-2023-04-23-PM-2572.jpg", "Morgan Freeman", "https://historyuk.s3.eu-west-2.amazonaws.com/s3fs-public/styles/768x432/public/2022-01/morgan%20freeman-min.jpg?itok=yEZRDGSQ", "Bob Gunton", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSiKDMy5LjN43ddR5H3loNJhnppVStBDCVUWw&s"], genre: ["درام"], quality: [480, 720, 1080], Isdubbed: true, summery: "در فیلم رستگاری در شاوشنک : اندی دوفرین بانکدار جوانی است که به جرم قتل همسر اش به حبس ابد در زندان ایالتی شائوشنک محکوم می شود. وی تأکید می کند که جرمی مرتکب نشده، ولی قاضی او را گناهکار اعلام میکند. او سالهای زیادی را در این زندان می گذراند. آلیس بوید رِدینگ یکی از زندانی های سیاه پوست است که به این شهرت دارد که می تواند هر چیزی را در زندان فراهم کند و ...", IsTopFilm: true, img: "https://www.imdb.com/title/tt0111161/mediaviewer/rm1690056449/?ref_=tt_ov_i", poster: "https://m.media-amazon.com/images/M/MV5BNTYxOTYyMzE3NV5BMl5BanBnXkFtZTcwOTMxNDY3Mw@@._V1_QL75_UX484.5_.jpg", url: "https://www.uptvs.com/play2?e=78950&dub=%D8%B1%D8%B3%D8%AA%DA%AF%D8%A7%D8%B1%DB%8C%20%D8%AF%D8%B1%20%D8%B4%D8%A7%D9%88%D8%B4%D9%86%DA%A9"
    },
    {
        title: "The Godfather", time: " 175 دقیقه ", year: 1972, imdbScore: 9.2, country: "آمریکا", IsTopFilm: true, director: "Francis Ford Coppola", stars: ["Francis Ford Coppola", "https://ca-times.brightspotcdn.com/dims4/default/67f759a/2147483647/strip/true/crop/3600x4505+0+0/resize/2000x2503!/quality/75/?url=https%3A%2F%2Fcalifornia-times-brightspot.s3.amazonaws.com%2F20%2F7b%2F43fa1c104895b17943be44b53b8f%2Fhttps-delivery-gettyimages.com%2Fdownloads%2F1506423441", "Al Pacino", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxFmdRCUk9PH5c-BJYBRHYGRsosYe180t57g&s"], genre: ["درام", "تراژدی", "جنایی"], quality: [480, 720, 1080], Isdubbed: true, summery: "فیلم در جشن عروسی کانی، دختر دون ویتو کورلئونه، در لانگ بیچ نیویورک، لانگ آیلند شروع می شود. وقت پدرخوانده برای شنیدن خواهش های دوستان و زیردستان چاپلوس پر شده است. یکی از این خواهش ها را پسرخوانده ی او، جانی فونتی خواننده مطرح می کند. آن خواهش چیست؟", img: "https://static1.srcdn.com/wordpress/wp-content/uploads/2023/05/the-godfather-poster.jpeg", poster: "https://assets.mubicdn.net/images/artworks/550926/images-original.png?1686641973", url: "https://www.uptvs.com/play2?e=67604&dub=%D9%BE%D8%AF%D8%B1%D8%AE%D9%88%D8%A7%D9%86%D8%AF%D9%87"
    },
    {
        title: "Schindler's List", time: " 195 دقیقه ", year: 1993, imdbScore: 9.0, country: "آمریکا", IsTopFilm: true, director: "    Steven Spielberg", stars: ["Liam Neeson", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqqjKu4hpofDyQmiiV8G-GTIWWoTV0IQRLQQ&s", "Ralph Fiennes", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRS17jD_DiWAhBc4sRW5g-KdxZJ5WmS7tu3OQ&s"], genre: ["درام", "زندگینامه", "تاریخی"], quality: [480, 720, 1080], Isdubbed: true, summery: " اسکار شیندلر طی سال‌های جنگ جهانی دوم در لهستان که به دست آلمان اشغال شده تلاش می‌کند تا کارگران یهودی خود را نجات داده و از اعزام آنها به اردوگاه‌های کار اجباری جلوگیری کند و...", poster: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.smithsonianmag.com%2Fhistory%2Fhow-schindlers-list-transformed-americans-understanding-of-the-holocaust-180983408%2F&psig=AOvVaw2PNPp0S9Y2-AIt1n-ihv11&ust=1726989674589000&source=images&cd=vfe&opi=89978449&ved=0CBMQjRxqFwoTCKDowJHA04gDFQAAAAAdAAAAABAJ", img: "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.amazon.com%2FSchindlers-List-Liam-Neeson%2Fdp%2FB07JJ5WH62&psig=AOvVaw2PNPp0S9Y2-AIt1n-ihv11&ust=1726989674589000&source=images&cd=vfe&opi=89978449&ved=0CBMQjRxqFwoTCKDowJHA04gDFQAAAAAdAAAAABAE", url: "https://www.uptvs.com/play2?e=107623&dub=%D9%81%D9%87%D8%B1%D8%B3%D8%AA%20%D8%B4%DB%8C%D9%86%D8%AF%D9%84%D8%B1"
    },
    {
        title: "Forrest Gump", time: "	142 دقیقه ", IsTopFilm: true, year: 1994, imdbScore: 8.8, director: "Robert Zemeckis", stars: ["Tom Hanks", "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.kennedy-center.org%2Fartists%2Fh%2Fha-hn%2Ftom-hanks%2F&psig=AOvVaw2lW2DTy5UrgRjpL8EMHfDA&ust=1726992246928000&source=images&cd=vfe&opi=89978449&ved=0CBMQjRxqFwoTCIiX_NvJ04gDFQAAAAAdAAAAABAE", "Robin Wright", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMMQeoA3IlQ1I2-vANlJu53FZPfALeixbdjg&s"], genre: ["زندگینامه", "درام", "رمانتیک"], country: "آمریکا", quality: [480, 720, 1080], Isdubbed: true, summery: " آی کیوی او در خردسالی زیر حد معمولی (۷۵) بود، شخصیت شیرین و عزیزی دارد و نسبت به عزیزان و وظایف خود از خود گذشته‌است. صفات شخصیتی او باعث می‌شود که موقعیت‌هایی برایش پیش آید که مسیر زندگیش را تغییر دهد. با پیش آمدن چنین موقعیت‌هایی او با رخدادها و شخصیت‌های برجسته تاریخ معاصر آمریکا مواجه می‌شود.", poster: "https://m.media-amazon.com/images/S/pv-target-images/0ad69b0fc33c51c85f1874652d0663a9c2b5063ae5b78580d5d4530c6917fc27._SX1080_FMjpg_.jpg", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBaNwbILJZZrhqpXUECVrPf1m8h3mw8dQWwA&s", url: "https://www.uptvs.com/play2?e=96738&dub=%D9%81%D8%A7%D8%B1%D8%B3%D8%AA%20%DA%AF%D8%A7%D9%85%D9%BE"
    },
    {
        title: "Fight Club", time: "139 دقیقه ", year: 1999, IsTopFilm: true, imdbScore: 8.8, director: "David Fincher", stars: [" Brad Pitt", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAbtBP6gWiUX1gxHahE59fWRf8B2pv-egVSQ&s", "Edward Norton", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTZOi9XZcRhgzBUc_fN8s3VkUbrNsgM9RGgQ&s"], genre: ["درام"], country: "آلمان", quality: [720, 1080], Isdubbed: true, summery: " «راوی»، جوانی پریشان، پی می‌برد که به کمک مشت‌بازی با دست‌های برهنه، بیش از هر زمان دیگری احساس زنده بودن می‌کند. او و «تایلر» که به دوستانی صمیمی تبدیل شده‌اند، هفته‌ای یک بار با هم ملاقات می‌کنند تا با هم مشت بازی کنند. در حالی که افراد دیگری هم به باشگاه‌شان می‌پیوندند، محفل‌شان به رغم آن که مخفی است بین شرکت کننده‌هایش، شهرت و محبوبیت یک باشگاه زیرزمینی را پیدا می‌کند و...", poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRanu-m1-UXm-Cbt0TPM313JoTHCA7aGRD3Hw&s", img: "https://media.posterlounge.com/img/products/770000/764906/764906_poster.jpg", url: "https://www.uptvs.com/play2?e=81354&dub=%D8%A8%D8%A7%D8%B4%DA%AF%D8%A7%D9%87%20%D9%85%D8%B4%D8%AA%20%D8%B2%D9%86%DB%8C"
    },
    // 
    , {
        title: "12 Angry Men", time: "96 دقیقه ", year: 1957, imdbScore: 9, IsTopFilm: true, genre: ["جنایی", "درام"], country: "	آمریکا ", Isdubbed: true, quality: [480, 720, 1080], director: "Sidney Lumet", stars: ["Henry Fonda", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFeMpCEQdsGJoyk5GH2SritquD5Rt4aExE9A&s", "Lee J. Cobb", "https://upload.wikimedia.org/wikipedia/commons/b/ba/Lee_J._Cobb_1960s.JPG"], summery: "فیلم درباره‌ی دوازده مرد در هیات منصفه یک دادگاه است که در زمان تنفس و قبل از اخذ رای نهایی دورهم جمع می‌شوند. همه اعضا معتقدند که مظنون گناهکار است. او یک پسر هجده ساله‌است که گمان می‌رود پدر خود را به قتل رسانده‌. یکی از اعضای هیات منصفه به‌نام دیوید با رای گناهکار بودن موافق نیست و شک‌هایی دارد باتوجه به این‌که تمام حقایق اثبات می‌کند که فرد مظنون گناهکار است، اعضا کنجکاو می‌شوند که چگونه دیوید دراین مورد مشکوک است و او دلایل خود را توضیح می‌دهد…", img: "https://musicart.xboxlive.com/7/b7805100-0000-0000-0000-000000000002/504/image.jpg?w=1920&h=1080", poster: "https://m.media-amazon.com/images/M/MV5BNGRlZjVhNWMtOTUxYi00MTYxLWEzOWUtMTM1NDc3ZWRjMDZjXkEyXkFqcGdeQWRpZWdtb25n._V1_.jpg", url: "https://www.uptvs.com/play2?e=91610&dub=12%20%D9%85%D8%B1%D8%AF%20%D8%AE%D8%B4%D9%85%DA%AF%DB%8C%D9%86"
    },
    {
        title: "Se7en", time: " 127 دقیقه ", year: 1995, imdbScore: 8.6, IsTopFilm: true, genre: ["جنایی", " درام "], country: "آمریکا", Isdubbed: true, quality: [480, 720, 1080], director: "David Fincher", stars: [" Brad Pitt", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAbtBP6gWiUX1gxHahE59fWRf8B2pv-egVSQ&s", "Morgan Freeman", "https://historyuk.s3.eu-west-2.amazonaws.com/s3fs-public/styles/768x432/public/2022-01/morgan%20freeman-min.jpg?itok=yEZRDGSQ"], summery: " بازرس نیلز جوان به قسمت جنایی اداره پلیس انتقال یافته و جانشین ویلیامز افسر مجرب پلیس می گردد. وقوع قتلهای زنجیره ای فجیع و ناتوانی او در امر دستگیری عامل آن باعث می شود كه ویلیامز به كمك او بشتابد.اما...", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhnYEQx15eUJpQU1BnEsuhSJeTGX_2EBSFdQ&s", poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSxB-4Lcxybi3gU9Alq0HeF5aS7Nrt_QR-nGA&s", url: "https://www.uptvs.com/play2?e=78821&dub=%D9%87%D9%81%D8%AA"
    },
    {
        title: "Gladiator", time: "155 دقیقه ", year: 2000, imdbScore: 8.5, IsTopFilm: true, genre: ["اکشن", "درام"], country: "آمریکا", Isdubbed: true, quality: [480, 720, 1080], director: "Ridley Scott", stars: ["Russell Crowe", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRVrxt-Ey6iluit5FDNlRJFgrdUrbSVvduavw&s", "Joaquin Phoenix", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGdwH6FMsXGEhvFbpN_6guQ2GvPkd-WKNcig&s", "Connie Nielsen", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv7w3dCobXYSjJC8XKAX11v8LUAUSvFVwSGQ&s"], summery: "", img: "", poster: "", url: ""
    },
    {
        title: "The Silence of the Lambs", time: " 118 دقیقه ", year: 1991, imdbScore: 8.6, IsTopFilm: true, genre: ["جنایی", " درام "], country: "آمریکا", Isdubbed: true, quality: [720, 1080], director: "Jonathan Demme", stars: ["Jodie Foster", "https://media.cnn.com/api/v1/images/stellar/prod/240108085520-jodie-foster-01-07-2024.jpg?c=original", "Anthony Hopkins", "https://images.mubicdn.net/images/cast_member/5224/cache-1533-1667731653/image-w856.jpg"], summery: "در فیلم سکوت بره‌ها کلاریس استارلینگ، کارآموز جوان FBI توسط جک کرافورد مأموریت می‌یابد که با هانیبال لکتر گفتگو نماید، زیرا ممکن است بتواند به آن‌ها در پیدا کردن بیل بوفالو که آدم‌کشی زنجیره‌ای است و پوست قربانیانش را از تن جدا می‌نماید، کمک نماید.", img: "https://play-lh.googleusercontent.com/NN4OtSReaguunuEfZftynIypKWaDBwA-AqmWdl8JKO0UrE3izMM9qoKH3q2ToIsn7Zw", poster: "https://www.indiependent.co.uk/wp-content/uploads/2021/01/silence-of-the-lambs-the-1991-007-anthony-hopkins-across-cell-glass-from-jodie-foster_1000x750.jpg", url: "https://www.uptvs.com/play2?e=75871&dub=%D8%B3%DA%A9%D9%88%D8%AA%20%D8%A8%D8%B1%D9%87%E2%80%8C%D9%87%D8%A7"
    }, {
        title: "The Irishman", time: "209 دقیقه ", year: 2019, imdbScore: 7.8, IsTopFilm: false, genre: ["بیوگرافی", "جنایی"], country: "آمریکا", Isdubbed: true, quality: [480, 720, 1080], director: "Martin Scorsese", stars: ["Al Pacino", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRxFmdRCUk9PH5c-BJYBRHYGRsosYe180t57g&s", "    Robert De Niro", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQGjitgEb6PoV8wCAgmF4kYzizgf8vgvVMBsQ&s"], summery: " طی دهه ۱۹۵۰ میلادی، یک راننده کامیون به نام فرانک شیرن، بخشی از محموله خود را به گانگسترهای محلی می‌فروشد و از این طریق با رهبر خانواده مافیایی بوفالینو ارتباط برقرار می‌کند. در ادامه، او همکاری خود را با این باند تبهکار آغاز می‌کند و...", img: "https://www.uptvs.com/wp-contents/uploads/2020/01/The-Irishman-2019.jpg", poster: "https://cdn.sargarme.com/uploads/2019/12/Irishman-Shakhes.jpg", url: "https://www.uptvs.com/play2?e=91907&upd=%D9%85%D8%B1%D8%AF%20%D8%A7%DB%8C%D8%B1%D9%84%D9%86%D8%AF%DB%8C"
    }
    , {

        title: "Chernobyl", time: "60 دقیقه ", imdbScore: 9.3, IsTopseries: true, day: "شنبه", genre: ["درام", "تاریخی", "حادثه ای"], country: "انگلستان", Isdubbed: true, quality: [480, 720, 1080, "FullHD"], director: "Johan Renck ", stars: ["Jessie Buckley", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZTysEgOZip-XS8RHsH8NcNsEkjiP4v0foNw&s", "Jared Harris", "https://m.media-amazon.com/images/M/MV5BODgyOTdjZjAtYmI2MS00ZjdhLTk0NzMtNGRhYjI4NTE3MjBhXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_.jpg"], notif: "قسمت 5 فصل 1 اضافه شد", summery: "در سریال چرنوبیل در آوریل 1986، انفجاری در تاسیسات هسته‌ای چرنوبیل در اوکراین رخ داد که باعث به وجود آمدن یکی از بدترین فجایع بشری در طول تاریخ شد و... «والری» نقشه‌ای دقیق را برای برطرف کردن آلودگی نیروگاه هسته‌ای چرنوبیل تدارک می‌بیند. از سوی دیگر، «لیودمیلا» هشدارهای مربوط به قرار گرفتن آتش‌نشان‌ها در معرض تشعشعات رادیواکتیو را نادیده می‌گیرد و...", img: "https://m.media-amazon.com/images/M/MV5BOTJiOWExNWEtYzE1ZS00NDJmLWFiY2ItYTNjMWZiNTQ2ZDIwXkEyXkFqcGc@._V1_.jpg", poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYi9FHwbRaJL6WSFzvtAK2vfuzjqBNdxlijg&s", url: "https://www.imdb.com/video/vi3724524825/?playlistId=tt7366338&ref_=tt_ov_vi"
    }
    , {

        title: "Breaking Bad", time: "45دقیقه ", imdbScore: 9.5, IsTopseries: true, day: "یکشنبه", genre: ["علمی", "درام", "جنایی"], country: "آمریکا", Isdubbed: true, quality: [480, 720, 1080], director: "Vince Gilligan", stars: ["Bryan Cranston", "https://www.geffenplayhouse.org/site/assets/files/4153/bryancranston-1000x1400.jpg", "Aaron Paul", "https://www.onthisday.com/images/people/aaron-paul.jpg?w=360", ""], notif: "قسمت آخر فصل پنجم قرار گرفت", summery: " درباره یک معلم شیمی میانسال است که متوجه می شود که دارای سرطان ریه است و ۲ سال بیشتر وقت برای زندگی ندارد. او که وضع مالی خوبی ندارد و دارای همسر و پسری معلول می باشد، به این فکر می افتد که باید قبل از مردن زندگی خانواده خود را تامین کند. پس با توجه به آشناییش به علم شیمی، همراه با یکی از شاگردان سابقش شروع به ساخت و فروش مواد مخدر می کند…", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdq0vuCeWF7fBJ7Dqc3kAzptsczMi_-1_ZXA&s", poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQjzbgcDjlt5Ng1oZrf8KvueF-QUKoAAFSF3g&s", url: "https://trailer.uptvs.com/trailer/Breaking-Bad-Trailer.mp4"
    }, {

        title: "The Sopranos", time: "60 دقیقه ", imdbScore: 9.2, IsTopseries: true, day: "شنبه", genre: ["جنایی", " درام "], country: "آمریکا", Isdubbed: false, quality: [, 720, 1080], director: "David Chase", stars: ["James Gandolfini", "https://m.media-amazon.com/images/M/MV5BMTkwMDY4NDMzN15BMl5BanBnXkFtZTcwNDkzNDE5NQ@@._V1_.jpg", "Lorraine Bracco", "https://stellaadler.com/wp-content/uploads/2019/02/lorraine-bracco.jpg"], notif: "فصل ششم قسمت 7 اضافه شد", summery: "سریال سوپرانو The Sopranos در مورد یک رئیس مافیای ایتالیایی آمریکایی به نام تونی سوپرانو است که با مسائل شخصی و کاری خود در زندگی دست و پنجه نرم می‌کند. حال این موضوع که بر وضعیت روانی سوپرانو تأثیر گذاشته است، وی را به سمت کمک از یک روانپزشک به نام جنیفر ملفی سوق می‌دهد و…", img: "https://m.media-amazon.com/images/M/MV5BZTZkMWVkNTEtYzMxMC00MzQzLTg5NjUtNTNmN2M2NzEwNzI0XkEyXkFqcGdeQXVyMTY3MDE5MDY1._V1_.jpg", poster: "https://observer.case.edu/wp-content/uploads/2021/08/MV5BM2NmZDNmYTItZGM0OS00NDVmLTgwMjUtZDdmYjg0OWNiODE2XkEyXkFqcGdeQXVyNDIyNjA2MTk@._V1_-900x506.jpg", url: "https://www.imdb.com/video/vi2751070489/?playlistId=tt0141842&ref_=tt_pr_ov_vi"
    }, {

        title: "The Perfect Couple", time: "60 دقیقه ", imdbScore: 6.6, IsTopseries: false, day: "دوشنبه", genre: ["جنایی", "درام", "معمایی"], country: "آمریکا", Isdubbed: false, quality: [480, 720, 1080], director: "Jenna Lamia", stars: ["Nicole Kidman", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTy7Bn6AabeO5lVPVg6ho8jxOYEZG0jE3PARw&s", "Liev Schreiber", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT97GrFwXhmhyAr9lNZ7iq2q7DbLRFb-NCECw&s"], notif: "قسمت آخر اضافه شد", summery: "در سریال زوج کامل The Perfect Couple 2024 آملیا در شرف ازدواج با یکی از ثروتمندترین خانواده‌های نانتاکت (یک جزیره در ایالات متحده) است، اما در این میان یک مرگ ناگهانی، عروسی را به هم می‌زند و همه را به مظنون تبدیل می‌کند و…", img: "https://m.media-amazon.com/images/M/MV5BMTRmNDBjNWEtODc5My00YjEyLWJlY2EtODhmYTcxYTcyMzRkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", poster: "https://dnm.nflximg.net/api/v6/BvVbc2Wxr2w6QuoANoSpJKEIWjQ/AAAAQRTYumBVvJUdTtnyS8HxCcisN0wOtz7VplS1vDHWidYgxGR0CUb1ZFKcMJcybtEOkeKuO-rC2_S1b9ABtdLY3lR8Uht2OKP2D_nA2l-XdQToCCuq3skAEAshL-j2jc52OAyA5N4M5bDSSP42GXGPpCU3HmM.jpg?r=6cb", url: "https://www.imdb.com/video/vi3093677593/?playlistId=tt11514868&ref_=tt_pr_ov_vi"
    }, {

        title: "Kaos", time: "60 دقیقه ", imdbScore: 7.5, IsTopseries: false, day: "سه شنبه", genre: ["کمدی", "فانتزی"], country: "انگلستان", Isdubbed: false, quality: [480, 720, 1080], director: "    Charlie Covell", stars: ["Jeff Goldblum", "https://i.guim.co.uk/img/media/f51585375a2c3ead7098c0fffb6d46658785882c/0_66_5792_6039/master/5792.jpg?width=465&dpr=1&s=none", "Janet McTeer", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgRoWAAhwV5uzKDk_l3yb4y5jxFZjC5noYEQ&s"], notif: "فصل اول اضافه شد", summery: "داستان سریال “Kaos” با زئوس، خدای قدرتمند ولی ناامن آغاز می‌شود. او وقتی متوجه یک چین و چروک روی پیشانی خود می‌شود، دچار ترس و پارانویا می‌گردد. زئوس باور دارد که این نشانه‌ای از پایان سلطنتش و در نهایت، پایان جهان است. این ترس او را به یک موجود انتقام‌جو تبدیل می‌کند. در همین حال، سه انسان به‌تدریج ارتباطات خود با یکدیگر و دخالت‌های خدایان یونانی در سرنوشتشان را کشف می‌کنند. این سه نفر باید با چالش‌های فراوانی روبرو شوند تا بتوانند مسیر درست را در برابر توطئه‌های بزرگ خدایان پیدا کنند.", img: "https://whsvikingtimes.com/wp-content/uploads/2024/09/625cd2bf-kaos__1200_1200__32-128-1030-1126.jpg", poster: "https://occ-0-8407-2219.1.nflxso.net/dnm/api/v6/E8vDc_W8CLv7-yMQu8KMEC7Rrr8/AAAABVGXT54topivEhiSdMTNRRmq7fBqF4iBg4Zc637-39vTMioTFimvzsHzujlU4mOZA-1RxLbr44PVCl8jv62M1toaCUcLQSblmsSV.jpg?r=e8f", url: "https://www.imdb.com/video/vi896976409/?playlistId=tt8550732&ref_=tt_pr_ov_vi"
    }, {

        title: "The Old Man", time: "61 دقیقه ", imdbScore: 7.6, IsTopseries: false, day: "چهارشنبه", genre: ["اکشن", "جاسوسی"], country: "آمریکا", Isdubbed: false, quality: [480, 720, 1080], director: "Robert Levine  & Jonathan E. Steinberg", stars: ["Jeff Bridges", "https://media.cnn.com/api/v1/images/stellar/prod/190102175805-top-unfurled-jeff-bridges.jpg?q=w_3000,c_fill", "John Lithgow", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeCoTrdOYa9ENrM5RikWKUGPZiHxwy01g-Ag&s"], notif: "قسمت 2 فصل دوم اضافه شد", summery: " یک مامور سابق سیا و کهنه‌سرباز افغانستان که به مدت سی سال به دور از شبکه در ورمونت زندگی می‌کند. زندگی آرام چیس زمانی به هم می‌ریزد که او به طور ناخواسته مجبور به کشتن یک مزاحم می‌شود که به خانه‌اش نفوذ کرده است. این حادثه باعث می‌شود که چیس مجبور به مخفی شدن شود و زندگی او به دنیای پیچیده و پرخطر جاسوسی بازگردد.", img: "https://m.media-amazon.com/images/M/MV5BZmMxNjU4YjgtYTNjOS00MzcxLWEyNjMtZmRjNDkxYjNlNGVkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg", poster: "https://ntvb.tmsimg.com/assets/p22067988_b_h8_aa.jpg?w=960&h=540", url: "https://www.imdb.com/video/vi3748709913/?playlistId=tt5645432&ref_=tt_ov_vi"
    }, {

        title: "Shōgun", time: "60 دقیقه ", imdbScore: 8.6, IsTopseries: true, day: "پنج شنبه", genre: ["ماجراجویی", "اکشن", "تاریخی"], country: "آمریکا", Isdubbed: true, quality: [480, 720, 1080], stars: ["Cosmo Jarvis", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTTUEOQlHtBvqAGenP5A6Ba1SDVjuVtw458Ag&s", "Anna Sawai", "https://i.mydramalist.com/1wg0nb_5c.jpg"], notif: "قسمت 10 فصل اول اضافه شد", summery: "در داستان “شوگان”، دو مرد جاه‌طلب از دو جهان مختلف و یک سامورایی زن مرموز دنبال می‌شوند. جان بلکثورن، ملوان انگلیسی ریسک‌پذیر که در آخرین پرواز خود به ژاپن غرق می‌شود و به یک سرزمین ناآشنا کشیده می‌شود. لرد توراناگا، یک زیرک دایمیو قدرتمند، در تقابل با رقبای خطرناک و سیاسی خود قرار دارد. و لیدی ماریکو، زنی با مهارت‌های ارزشمند، اما در مواجهه با روابط خانوادگی بی‌شرف قرار دارد و باید ارزش و وفاداری خود را ثابت کند.", img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkkJDzWJ9S2bVvncWUVjjKA3NFlPex0ppGvA&s", poster: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRw3APa8rnjfxaHY3p1410WIUC-8R-EEZ3SFyPGg3b2C8mN6F4pm4EgUVlPP3pD6iSoLok&usqp=CAU", url: "https://www.imdb.com/video/vi2821244441/?playlistId=tt2788316&ref_=tt_ov_vi"
    }
]
export{movies}